#!/bin/bash

PACMAN_INSTALL="sudo pacman -S --noconfirm --needed"
YAY_INSTALL="yay -S --removemake --noconfirm --needed"

pacman -Qq pacman &> /dev/null || (echo "Not running on Arch!" && exit)

# Clone submodules
git submodule update --init

# Refresh mirrors
source bin/refresh-mirrorlist

# Install base-devel group
$PACMAN_INSTALL base-devel || exit

# Patch pacman.conf
sudo patch -d/ -p0 -Nr- -i $PWD/system/pacman.patch

# Update packages
sudo pacman -Syu

# Install yay
source bin/install-yay

# Install packages
$YAY_INSTALL - < packages/aur
$YAY_INSTALL - < packages/native

# Patch lightdm
sudo patch -d/ -p0 -Nr- -i $PWD/system/lightdm.patch

# systemd services
xargs sudo systemctl enable < system/services

# Application settings
mkdir -p $HOME/.config
find config -exec cp {} -rf $HOME/.config \;

# Cinnamon settings
mkdir -p $HOME/.cinnamon
find cinnamon/configs -exec cp -rf {} $HOME/.cinnamon \;

# dconf settings
dconf load / < cinnamon/all.conf

# Copy dotfiles
find dotfiles -name '.*' ! -name '.git' -exec cp -rf {} $HOME \;
